meta-buv-runbmc: fix postinstall scriptlets error
ERROR: obmc-phosphor-image-1.0-r0 do_rootfs: Postinstall scriptlets of
['first-boot-set-psu'] have failed. If the intention is to defer them to
first boot, then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

Signed-off-by: Ban Feng <kcfeng0@nuvoton.com>